### ISSUE TITLE
MOFF score GOP statistic

### ISSUE THREAD

**Issue by lvbakker** [MDhewei/MOFF#2]
Hi,

I ran the MOFF score -i input.csv functionality and now my output file shows me the "GOP" column.
What does this column mean? I cannot seem to find anything about it. 

with kind regards,
Linda

**Comment by MDhewei** [comment]
Hi Linda,

GOP is short for Guide off-target potential, which is the global off-target potential for one gRNA trained on single-mismatch data, the final GMT equals GOP**(number of mismatch).

Best,
Wei

**Comment by lvbakker** [comment]
Thank you!
